name: News Request
description: Make a news request
title: "[NEWS REQUEST]: "
labels: ["news", "web"]
body:
  - type: input
    id: news-title-en
    attributes:
      label: Title in English
    validations:
      required: true
  - type: textarea
    id: news-body-en
    attributes:
      label: Text in English
      value: "Please input the article body in English"
    validations:
      required: true
  - type: input
    id: news-title-tr
    attributes:
      label: Title in Turkish
    validations:
      required: true
  - type: textarea
    id: news-body-tr
    attributes:
      label: Text in Turkish
      value: "Please input the article body in Turkish"
    validations:
      required: true
  - type: textarea
    id: news-extra
    attributes:
      label: Any thumbnail images?
      description: |
        You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Consent
      options:
        - label: I, hereby, declare that all information supplied for the article is accurate and has been consented to by their respective stakeholders.
          required: true
